language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t rommelrico/complex-client-test ./client

script:
  - docker run -e CI=true rommelrico/complex-client-test npm run test -- --coverage src

after_success:
  - docker build -t rommelrico/complex-client ./client
  - docker build -t rommelrico/complex-nginx ./nginx
  - docker build -t rommelrico/complex-server ./server
  - docker build -t rommelrico/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rommelrico/complex-client
  - docker push rommelrico/complex-nginx
  - docker push rommelrico/complex-server
  - docker push rommelrico/complex-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'complex-docker'
  env: 'complex-docker-env'
  bucket_name: "elasticbeanstalk-us-west-1-311766412877"
  bucket_path: 'complex-docker-bucket'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
